### PR TITLE
Fix/44 Add tests

### LINKED ISSUE #44: Add tests
## Describe the Issue

Currently, there are no tests for `frontend` and `backend`. We should add the tests for quality and reliability.

## Additional Context

Main tool would be `Jest`
- for `frontend`:
We can use [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

### PR DESCRIPTION
**Pull request by karanBRAVO**
## Describe the PR

In this PR, I have added the configuration files for writing tests in both frontend and backend. Using `Vitest` as the testing framework.
Resolves #44 

## How to test this PR

1. Install the dependencies
```bash
npm ci
```
2. To run frontend tests
```bash
npm run test:frontend
```
3. To run backend tests
```bash
npm run test:backend
```

### CODE REVIEW

**Comment by Monokaix** [comment]
You can rebase the master branch first: )

**Comment by karanBRAVO** [comment]
> You can rebase the master branch first: )

ok

**Comment by karanBRAVO** [comment]
Hello @Monokaix,
I have updated the PR, need your reviews. let me know if there's any issue.
Thanks
Karan Yadav

File: frontend/src/components/Layout.jsx [hunk 1]
```diff
@@ -76,6 +76,7 @@ const Layout = () => {
             </AppBar>
 
             <Drawer
+                data-testid="sidebar-drawer"
```
Comment (karanBRAVO) [inline frontend/src/components/Layout.jsx:79]: `id` given to this component so that it is easier to get this while testing.

File: frontend/vitest.config.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+        },
+        // browser: {
+        //     provider: "playwright",
+        //     enabled: true,
+        //     instances: [
+        //         {
+        //             browser: "chromium",
+        //         },
+        //     ],
+        // },
```
Comment (karanBRAVO) [inline frontend/vitest.config.js:21]: This is useful when we want to run tests in the browser natively.
https://vitest.dev/guide/browser/

**Comment by Monokaix** [comment]
Does this pr only add a test framework？And why choose vitest？

**Comment by karanBRAVO** [comment]
> Does this pr only add a test framework？And why choose vitest？

Yes, this adds the test framework `vitest`, also 2 tests to check this PR.

## Why Vitest

Since we are use `vite.js` so `vitest` is the natural choice, and it provides better `Dev Experience` as it has interactive `ui`. Along with that, it is fast and similar to `jest`.

**Comment by karanBRAVO** [comment]
Hey @Monokaix, rebased the PR, let me know if there's any other issue.

File: frontend/vitest.config.js (hunk 2 above)
Comment (Monokaix) [reply frontend/vitest.config.js:21]: Why comment this?

Comment (karanBRAVO) [reply frontend/vitest.config.js:21]: > Why comment this?

because this is `Experimental` feature.

**Review by kevin-wangzefeng — COMMENTED** [review]
/approve

**Comment by Monokaix** [comment]
Hi please rebase the master and keep one clean commit: )

**Comment by karanBRAVO** [comment]
Hello @Monokaix, I have updated the commits, let me know if there's any other issue(s). :)

File: backend/vitest.config.js [hunk 3]
```diff
@@ -0,0 +1,12 @@
+import { defineConfig } from "vitest/config";
```
[the remark this answers is not in the document]
Comment (karanBRAVO) [reply backend/vitest.config.js:1]: +1

[the remark this answers is not in the document]
Comment (Monokaix) [reply backend/vitest.config.js:1]: Yeah you can keep working on that @de6p ！

**Comment by karanBRAVO** [comment]
Hey @Monokaix, Now we have to write tests. Should I create `issue` related to this? Also, I wanna work on this.
Do we have to keep this for next LFX mentorship program?

**Comment by Monokaix** [comment]
> Hey @Monokaix, Now we have to write tests. Should I create `issue` related to this? Also, I wanna work on this. Do we have to keep this for next LFX mentorship program?

Maybe we can consider that: )
